### ISSUE TITLE
SensorContext::newCoverage

### ISSUE THREAD

**Issue by omgapuppy** [sfeir-open-source/sonar-clover#14]
```
:build
:cloverAggregateDatabases
:cloverGenerateReport
:sonarqube
Coverage measure for metric 'lines_to_cover' should not be saved directly by a Sensor. Plugin should be updated to use SensorContext::newCoverage instead.
Coverage measure for metric 'uncovered_lines' should not be saved directly by a Sensor. Plugin should be updated to use SensorContext::newCoverage instead.
Coverage measure for metric 'coverage_line_hits_data' should not be saved directly by a Sensor. Plugin should be updated to use SensorContext::newCoverage instead.
Coverage measure for metric 'conditions_to_cover' should not be saved directly by a Sensor. Plugin should be updated to use SensorContext::newCoverage instead.
Coverage measure for metric 'uncovered_conditions' should not be saved directly by a Sensor. Plugin should be updated to use SensorContext::newCoverage instead.
Coverage measure for metric 'conditions_by_line' should not be saved directly by a Sensor. Plugin should be updated to use SensorContext::newCoverage instead.
Coverage measure for metric 'covered_conditions_by_line' should not be saved directly by a Sensor. Plugin should be updated to use SensorContext::newCoverage instead.
CodeNarc completed: (p1=0; p2=19; p3=0) 2601ms
Metric 'lines' is an internal metric computed by SonarQube. Provided value is ignored.
Metric 'test_success_density' is an internal metric computed by SonarQube. Provided value is ignored.
```

**Comment by mlschechter** [comment]
This should be addressed by my [pull request](https://github.com/Tony-Proum/sonar-clover/pull/15). Please let me know if you have any questions.

**Comment by omgapuppy** [comment]
@mlschechter thanks for the heads-up!

**Comment by Tony-Proum** [comment]
@mlschechter I've tested your pull request and it doesn't address this issue, I'm still getting those outputs.
```
[INFO] Sensor org.sonar.plugins.clover.CloverSensor [clover]
[INFO] Parsing /home/tony/myproject/target/site/clover/clover.xml
[WARNING] Coverage measure for metric 'lines_to_cover' should not be saved directly by a Sensor. Plugin should be updated to use SensorContext::newCoverage instead.
[WARNING] Coverage measure for metric 'uncovered_lines' should not be saved directly by a Sensor. Plugin should be updated to use SensorContext::newCoverage instead.
[WARNING] Coverage measure for metric 'coverage_line_hits_data' should not be saved directly by a Sensor. Plugin should be updated to use SensorContext::newCoverage instead.
[WARNING] Coverage measure for metric 'conditions_to_cover' should not be saved directly by a Sensor. Plugin should be updated to use SensorContext::newCoverage instead.
[WARNING] Coverage measure for metric 'uncovered_conditions' should not be saved directly by a Sensor. Plugin should be updated to use SensorContext::newCoverage instead.
[WARNING] Coverage measure for metric 'conditions_by_line' should not be saved directly by a Sensor. Plugin should be updated to use SensorContext::newCoverage instead.
[WARNING] Coverage measure for metric 'covered_conditions_by_line' should not be saved directly by a Sensor. Plugin should be updated to use SensorContext::newCoverage instead.

```

**Comment by mlschechter** [comment]
@Tony-Proum - my code does not store those metrics directly; I specifically had to modify the XML parser test to account for this.

Do you see these same warnings in the integration tests?

**Comment by mlschechter** [comment]
@Tony-Proum,

Just ran the integration tests locally from my pull request branch; the output is below.

Please let me know if there's anything else you need.
 
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin/java -Dsonar.runtimeVersion=6.7.1 -server -Didea.test.cyclic.buffer.size=5242880 "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=55061:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit-rt.jar:/Applications/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit5-rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/lib/tools.jar:/Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/test-classes:/Users/ms185252/.m2/repository/org/sonarsource/orchestrator/sonar-orchestrator/3.15.2.1322/sonar-orchestrator-3.15.2.1322.jar:/Users/ms185252/.m2/repository/org/codehaus/sonar/sonar-ws-client/4.5/sonar-ws-client-4.5.jar:/Users/ms185252/.m2/repository/org/sonarsource/update-center/sonar-update-center-common/1.21.0.561/sonar-update-center-common-1.21.0.561.jar:/Users/ms185252/.m2/repository/com/squareup/okhttp3/okhttp/3.6.0/okhttp-3.6.0.jar:/Users/ms185252/.m2/repository/com/squareup/okio/okio/1.11.0/okio-1.11.0.jar:/Users/ms185252/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/ms185252/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/Users/ms185252/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar:/Users/ms185252/.m2/repository/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar:/Users/ms185252/.m2/repository/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar:/Users/ms185252/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:/Users/ms185252/.m2/repository/org/apache/httpcomponents/httpmime/4.5.2/httpmime-4.5.2.jar:/Users/ms185252/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar:/Users/ms185252/.m2/repository/com/h2database/h2/1.3.172/h2-1.3.172.jar:/Users/ms185252/.m2/repository/ch/qos/logback/logback-classic/1.1.7/logback-classic-1.1.7.jar:/Users/ms185252/.m2/repository/ch/qos/logback/logback-core/1.1.7/logback-core-1.1.7.jar:/Users/ms185252/.m2/repository/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.jar:/Users/ms185252/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.2/jcl-over-slf4j-1.7.2.jar:/Users/ms185252/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.2/log4j-over-slf4j-1.7.2.jar:/Users/ms185252/.m2/repository/junit/junit/4.12/junit-4.12.jar:/Users/ms185252/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/ms185252/.m2/repository/org/easytesting/fest-assert/1.4/fest-assert-1.4.jar:/Users/ms185252/.m2/repository/org/easytesting/fest-util/1.1.6/fest-util-1.1.6.jar:/Users/ms185252/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar" com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit4 com.sonar.clover.it.CloverTest
08:00:48.504 WARN  Using default value for orchestrator.properties: sonar.jdbc.dialect=embedded
08:00:48.510 WARN  Using default value for orchestrator.properties: orchestrator.updateCenterUrl=http://update.sonarsource.org/update-center-dev.properties
08:00:48.510 WARN  Using default value for orchestrator.properties: maven.localRepository=/Users/ms185252/.m2/repository
08:00:48.677 INFO  Downloading: http://update.sonarsource.org/update-center-dev.properties
08:00:53.464 INFO  Register JDBC driver: org.h2.Driver
08:00:53.613 INFO  Executing command: unzip -o -q /Users/ms185252/.sonar/installs/sonarqube-6.7.1.zip
08:00:55.816 INFO  Remove distribution plugins
08:00:55.822 INFO  Unable to find plugin java in Maven repository. Fallback to use update center URL
08:00:55.822 INFO  Downloading: https://sonarsource.bintray.com/Distribution/sonar-java-plugin/sonar-java-plugin-5.6.1.15064.jar
08:01:01.396 INFO  Installed plugin: sonar-java-plugin-5.6.1.15064.jar
08:01:01.398 INFO  Unable to find plugin groovy in Maven repository. Fallback to use update center URL
08:01:01.398 INFO  Downloading: https://github.com/SonarQubeCommunity/sonar-groovy/releases/download/1.5/sonar-groovy-plugin-1.5.jar
08:01:22.199 INFO  Installed plugin: sonar-groovy-plugin-1.5.jar
08:01:22.281 INFO  Installed plugin: sonar-clover-plugin.jar
08:01:22.282 INFO  Installed plugin: sonar-reset-data-plugin-1.0-SNAPSHOT.jar
08:01:22.298 INFO  Start server 6.7.1 from /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/1/sonarqube-6.7.1
> 08:01:22.760 [main] WARN org.sonar.application.config.JdbcSettings - Both 'sonar.embeddedDatabase.port' and 'sonar.jdbc.url' properties are set. The value of property 'sonar.jdbc.url' ('jdbc:h2:tcp://127.0.0.1:55067/sonar;USER=sonar;PASSWORD=sonar') is not consistent with the value of property 'sonar.embeddedDatabase.port' ('55067'). The value of property 'sonar.jdbc.url' will be ignored and value 'jdbc:h2:tcp://127.0.0.1:55067/sonar' will be used instead. To remove this warning, either remove property 'sonar.jdbc.url' if your intent was to use the embedded H2 database, otherwise remove property 'sonar.embeddedDatabase.port'.
> 2018.08.23 08:01:22 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/1/sonarqube-6.7.1/temp
> 2018.08.23 08:01:22 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:55076
> 2018.08.23 08:01:22 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/1/sonarqube-6.7.1/elasticsearch]: /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/1/sonarqube-6.7.1/elasticsearch/bin/elasticsearch -Epath.conf=/Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/1/sonarqube-6.7.1/temp/conf/es
> 2018.08.23 08:01:23 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
> 2018.08.23 08:01:23 INFO  app[][o.e.p.PluginsService] no modules loaded
> 2018.08.23 08:01:23 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
> 2018.08.23 08:01:30 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
> 2018.08.23 08:01:30 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/1/sonarqube-6.7.1]: /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/1/sonarqube-6.7.1/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -cp ./lib/common/*:./lib/server/*:/Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/1/sonarqube-6.7.1/lib/jdbc/h2/h2-1.3.176.jar org.sonar.server.app.WebServer /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/1/sonarqube-6.7.1/temp/sq-process4008474869796972630properties
> 2018.08.23 08:01:31 INFO  web[][o.s.p.ProcessEntryPoint] Starting web
> 2018.08.23 08:01:31 INFO  web[][o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
> 2018.08.23 08:01:32 INFO  web[][o.e.p.PluginsService] no modules loaded
> 2018.08.23 08:01:32 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
> 2018.08.23 08:01:32 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
> 2018.08.23 08:01:32 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
> 2018.08.23 08:01:32 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
> 2018.08.23 08:01:34 INFO  web[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [127.0.0.1:55076]
> 2018.08.23 08:01:34 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 6.7.1.35068 / 426519346f51f7b980a76f9050f983110550509d
> 2018.08.23 08:01:34 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Starting embedded database on port 55067 with url jdbc:h2:tcp://127.0.0.1:55067/sonar
> 2018.08.23 08:01:34 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Embedded database started. Data stored in: /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/1/sonarqube-6.7.1/data
> 2018.08.23 08:01:34 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:h2:tcp://127.0.0.1:55067/sonar
> 2018.08.23 08:01:34 WARN  web[][o.s.d.DatabaseChecker] H2 database should be used for evaluation purpose only
> 2018.08.23 08:01:35 INFO  web[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/1/sonarqube-6.7.1
> 2018.08.23 08:01:35 INFO  web[][o.s.s.u.SystemPasscodeImpl] System authentication by passcode is disabled
> 2018.08.23 08:01:35 INFO  web[][o.s.s.p.d.m.h.MigrationHistoryTableImpl] Creating table schema_migrations
> 2018.08.23 08:01:35 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin Clover [clover] installed
> 2018.08.23 08:01:35 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin Groovy [groovy] installed
> 2018.08.23 08:01:35 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarJava [java] installed
> 2018.08.23 08:01:35 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin Orchestrator :: Reset data [resetdata] installed
> 2018.08.23 08:01:35 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Clover / 3.2-SNAPSHOT / ef99ecf30cf0eb884b39305bc63897df5405e277
> 2018.08.23 08:01:35 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Groovy / 1.5 / dcbcd1eeb8f61c8351e5dd1e51e11e52d186df35
> 2018.08.23 08:01:35 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Orchestrator :: Reset data / 1.0-SNAPSHOT
> 2018.08.23 08:01:35 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarJava / 5.6.1.15064 / dd4545a04af6f7d0cb0486926cfa8cfc5cae5ee1
> 2018.08.23 08:01:35 INFO  web[][o.s.s.p.d.m.AutoDbMigration] Automatically perform DB migration on fresh install
> 2018.08.23 08:01:36 INFO  web[][o.s.s.p.Platform] Database has been automatically updated
> 2018.08.23 08:01:36 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.ws.WebServiceFilter@69abb4df [pattern=UrlPattern{inclusions=[/api/system/migrate_db/*, ...], exclusions=[/api/properties*, ...]}]
> 2018.08.23 08:01:36 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 55075
> 2018.08.23 08:01:37 INFO  web[][o.s.s.p.UpdateCenterClient] Update center: https://update.sonarsource.org/update-center.properties (no proxy)
> 2018.08.23 08:01:37 INFO  web[][o.s.s.e.IndexCreator] Create index metadatas
> 2018.08.23 08:01:38 INFO  web[][o.s.s.e.IndexCreator] Create type metadatas/metadata
> 2018.08.23 08:01:38 INFO  web[][o.s.s.e.IndexCreator] Create index components
> 2018.08.23 08:01:39 INFO  web[][o.s.s.e.IndexCreator] Create type components/component
> 2018.08.23 08:01:39 INFO  web[][o.s.s.e.IndexCreator] Create type components/authorization
> 2018.08.23 08:01:39 INFO  web[][o.s.s.e.IndexCreator] Create index tests
> 2018.08.23 08:01:39 INFO  web[][o.s.s.e.IndexCreator] Create type tests/test
> 2018.08.23 08:01:39 INFO  web[][o.s.s.e.IndexCreator] Create index projectmeasures
> 2018.08.23 08:01:40 INFO  web[][o.s.s.e.IndexCreator] Create type projectmeasures/projectmeasure
> 2018.08.23 08:01:40 INFO  web[][o.s.s.e.IndexCreator] Create type projectmeasures/authorization
> 2018.08.23 08:01:40 INFO  web[][o.s.s.e.IndexCreator] Create index rules
> 2018.08.23 08:01:40 INFO  web[][o.s.s.e.IndexCreator] Create type rules/activeRule
> 2018.08.23 08:01:40 INFO  web[][o.s.s.e.IndexCreator] Create type rules/ruleExtension
> 2018.08.23 08:01:40 INFO  web[][o.s.s.e.IndexCreator] Create type rules/rule
> 2018.08.23 08:01:40 INFO  web[][o.s.s.e.IndexCreator] Create index issues
> 2018.08.23 08:01:41 INFO  web[][o.s.s.e.IndexCreator] Create type issues/issue
> 2018.08.23 08:01:41 INFO  web[][o.s.s.e.IndexCreator] Create type issues/authorization
> 2018.08.23 08:01:41 INFO  web[][o.s.s.e.IndexCreator] Create index users
> 2018.08.23 08:01:41 INFO  web[][o.s.s.e.IndexCreator] Create type users/user
> 2018.08.23 08:01:41 INFO  web[][o.s.s.e.IndexCreator] Create index views
> 2018.08.23 08:01:42 INFO  web[][o.s.s.e.IndexCreator] Create type views/view
> 2018.08.23 08:01:42 INFO  web[][o.s.s.s.LogServerId] Server ID: AWVmqU7Bj2lG-KH_Xj3z
> 2018.08.23 08:01:42 INFO  web[][o.s.s.t.TelemetryDaemon] Sharing of SonarQube statistics is enabled.
> 2018.08.23 08:01:42 INFO  web[][o.s.s.n.NotificationDaemon] Notification service started (delay 60 sec.)
> 2018.08.23 08:01:42 INFO  web[][o.s.s.s.GeneratePluginIndex] Generate scanner plugin index
> 2018.08.23 08:01:42 INFO  web[][o.s.s.s.RegisterPlugins] Register plugins
> 2018.08.23 08:01:42 INFO  web[][o.s.s.s.RegisterMetrics] Register metrics
> 2018.08.23 08:01:42 INFO  web[][o.s.s.r.RegisterRules] Register rules
> 2018.08.23 08:01:46 INFO  web[][o.s.s.q.BuiltInQProfileRepositoryImpl] Load quality profiles
> 2018.08.23 08:01:46 INFO  web[][o.s.s.q.RegisterQualityProfiles] Register quality profiles
> 2018.08.23 08:01:46 INFO  web[][o.s.s.q.RegisterQualityProfiles] Register profile java/Sonar way
> 2018.08.23 08:01:47 INFO  web[][o.s.s.q.RegisterQualityProfiles] Register profile grvy/Sonar way
> 2018.08.23 08:01:47 INFO  web[][o.s.s.s.RegisterPermissionTemplates] Register permission templates
> 2018.08.23 08:01:47 INFO  web[][o.s.s.s.RenameDeprecatedPropertyKeys] Rename deprecated property keys
> 2018.08.23 08:01:47 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.ws.WebServiceFilter@aec739 [pattern=UrlPattern{inclusions=[/api/measures/component/*, ...], exclusions=[/api/properties*, ...]}]
> 2018.08.23 08:01:47 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.ws.DeprecatedPropertiesWsFilter@404ae084 [pattern=UrlPattern{inclusions=[/api/properties/*], exclusions=[]}]
> 2018.08.23 08:01:47 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.ws.WebServiceReroutingFilter@30cd0305 [pattern=UrlPattern{inclusions=[/api/components/bulk_update_key, ...], exclusions=[]}]
> 2018.08.23 08:01:47 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.InitFilter@49d3a66 [pattern=UrlPattern{inclusions=[/sessions/init/*], exclusions=[]}]
> 2018.08.23 08:01:47 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.OAuth2CallbackFilter@544e542 [pattern=UrlPattern{inclusions=[/oauth2/callback/*], exclusions=[]}]
> 2018.08.23 08:01:47 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.ws.LoginAction@6b2aa454 [pattern=UrlPattern{inclusions=[/api/authentication/login], exclusions=[]}]
> 2018.08.23 08:01:47 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.ws.LogoutAction@5cbc4a35 [pattern=UrlPattern{inclusions=[/api/authentication/logout], exclusions=[]}]
> 2018.08.23 08:01:47 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.ws.ValidateAction@2b4de98c [pattern=UrlPattern{inclusions=[/api/authentication/validate], exclusions=[]}]
> 2018.08.23 08:01:47 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of type [rules/activeRule] ...
> 2018.08.23 08:01:48 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of type [rules/activeRule] done | time=688ms
> 2018.08.23 08:01:48 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of types [rules/ruleExtension],[rules/rule] ...
> 2018.08.23 08:01:49 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of types [rules/ruleExtension],[rules/rule] done | time=1107ms
> 2018.08.23 08:01:49 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of type [users/user] ...
> 2018.08.23 08:01:49 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of type [users/user] done | time=213ms
> 2018.08.23 08:01:49 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of type [components/component] ...
> 2018.08.23 08:01:49 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of type [components/component] done | time=144ms
> 2018.08.23 08:01:49 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of type [views/view] ...
> 2018.08.23 08:01:49 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of type [views/view] done | time=136ms
> 2018.08.23 08:01:49 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of type [issues/issue] ...
> 2018.08.23 08:01:49 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of type [issues/issue] done | time=138ms
> 2018.08.23 08:01:49 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of types [components/authorization],[issues/authorization],[projectmeasures/authorization] ...
> 2018.08.23 08:01:50 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of types [components/authorization],[issues/authorization],[projectmeasures/authorization] done | time=268ms
> 2018.08.23 08:01:50 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of type [tests/test] ...
> 2018.08.23 08:01:50 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of type [tests/test] done | time=79ms
> 2018.08.23 08:01:50 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of type [projectmeasures/projectmeasure] ...
> 2018.08.23 08:01:50 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of type [projectmeasures/projectmeasure] done | time=78ms
> 2018.08.23 08:01:50 INFO  web[][o.s.s.p.Platform] WebServer is operational
> 2018.08.23 08:01:50 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up
> 2018.08.23 08:01:50 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='ce', ipcIndex=3, logFilenamePrefix=ce]] from [/Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/1/sonarqube-6.7.1]: /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/1/sonarqube-6.7.1/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -cp ./lib/common/*:./lib/server/*:./lib/ce/*:/Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/1/sonarqube-6.7.1/lib/jdbc/h2/h2-1.3.176.jar org.sonar.ce.app.CeServer /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/1/sonarqube-6.7.1/temp/sq-process8305114014116375133properties
> 2018.08.23 08:01:50 INFO  ce[][o.s.p.ProcessEntryPoint] Starting ce
> 2018.08.23 08:01:50 INFO  ce[][o.s.ce.app.CeServer] Compute Engine starting up...
> 2018.08.23 08:01:51 INFO  ce[][o.e.p.PluginsService] no modules loaded
> 2018.08.23 08:01:51 INFO  ce[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
> 2018.08.23 08:01:51 INFO  ce[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
> 2018.08.23 08:01:51 INFO  ce[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
> 2018.08.23 08:01:51 INFO  ce[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
> 2018.08.23 08:01:52 INFO  ce[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [127.0.0.1:55076]
> 2018.08.23 08:01:52 INFO  ce[][o.sonar.db.Database] Create JDBC data source for jdbc:h2:tcp://127.0.0.1:55067/sonar
> 2018.08.23 08:01:52 WARN  ce[][o.s.d.DatabaseChecker] H2 database should be used for evaluation purpose only
> 2018.08.23 08:01:53 INFO  ce[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/1/sonarqube-6.7.1
> 2018.08.23 08:01:53 INFO  ce[][o.s.c.c.CePluginRepository] Load plugins
> 2018.08.23 08:01:54 INFO  ce[][o.s.c.q.PurgeCeActivities] Delete the Compute Engine tasks created before Sat Feb 24 08:01:54 EST 2018
> 2018.08.23 08:01:54 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is operational
> 2018.08.23 08:01:54 INFO  app[][o.s.a.SchedulerImpl] Process[ce] is up
> 2018.08.23 08:01:54 INFO  app[][o.s.a.SchedulerImpl] SonarQube is up
08:01:54.600 INFO  Execute: /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/sonar-scanner-2.8/bin/sonar-scanner -e -Dsonar.clover.reportPath=clover.xml -Dsonar.java.coveragePlugin=clover -Dsonar.sourceEncoding=UTF-8 -Dsonar.projectName=reuseReport -Dsonar.projectKey=reuseReport -Dsonar.host.url=http://127.0.0.1:55075 -Dsonar.projectVersion=1.0 -Dsonar.sources=src/main/java -Dsonar.java.binaries=target/classes -Dsonar.scm.disabled=true
INFO: Option -e/--errors is no longer supported and will be ignored
INFO: Scanner configuration file: /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/sonar-scanner-2.8/conf/sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: SonarQube Scanner 2.8
INFO: Java 1.8.0_171 Oracle Corporation (64-bit)
INFO: Mac OS X 10.12.6 x86_64
INFO: User cache: /Users/ms185252/.sonar/cache
INFO: Publish mode
INFO: Load global settings
INFO: Load global settings (done) | time=99ms
INFO: Server id: AWVmqU7Bj2lG-KH_Xj3z
INFO: User cache: /Users/ms185252/.sonar/cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=48ms
INFO: Download sonar-clover-plugin.jar
INFO: Download sonar-java-plugin-5.6.1.15064.jar
INFO: SonarQube server 6.7.1
INFO: Default locale: "en_US", source code encoding: "UTF-8"
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=13ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=48ms
INFO: Load active rules
INFO: Load active rules (done) | time=642ms
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=41ms
INFO: Project key: reuseReport
INFO: -------------  Scan reuseReport
INFO: Load server rules
INFO: Load server rules (done) | time=83ms
INFO: Base dir: /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/projects/reuseReport
INFO: Working dir: /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/projects/reuseReport/.sonar
INFO: Source paths: src/main/java
INFO: Source encoding: UTF-8, default locale: en_US
INFO: Index files
INFO: 3 files indexed
INFO: Quality profile for java: Sonar way
INFO: Sensor JavaSquidSensor [java]
INFO: Configured Java source version (sonar.java.source): none
INFO: JavaClasspath initialization
WARN: Bytecode of dependencies was not provided for analysis of source files, you might end up with less precise results. Bytecode can be provided using sonar.java.libraries property
INFO: JavaClasspath initialization (done) | time=10ms
INFO: JavaTestClasspath initialization
INFO: JavaTestClasspath initialization (done) | time=1ms
INFO: Java Main Files AST scan
INFO: 3 source files to be analyzed
INFO: 3/3 source files have been analyzed
INFO: Java Main Files AST scan (done) | time=841ms
INFO: Java Test Files AST scan
INFO: 0 source files to be analyzed
INFO: 0/0 source files have been analyzed
INFO: Java Test Files AST scan (done) | time=1ms
INFO: Sensor JavaSquidSensor [java] (done) | time=1413ms
INFO: Sensor Clover Coverage Analysis [clover]
INFO: Parsing /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/projects/reuseReport/clover.xml
INFO: Matched files in report : 100%
INFO: Sensor Clover Coverage Analysis [clover] (done) | time=76ms
INFO: Sensor SurefireSensor [java]
INFO: parsing [/Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/projects/reuseReport/target/surefire-reports]
INFO: Sensor SurefireSensor [java] (done) | time=3ms
INFO: Sensor JaCoCoSensor [java]
INFO: Sensor JaCoCoSensor [java] (done) | time=1ms
INFO: Sensor SonarJavaXmlFileSensor [java]
INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=1ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=10ms
INFO: Sensor CPD Block Indexer
INFO: Sensor CPD Block Indexer (done) | time=16ms
INFO: SCM Publisher is disabled
INFO: 1 file had no CPD blocks
INFO: Calculating CPD for 2 files
INFO: CPD calculation finished
INFO: Analysis report generated in 72ms, dir size=20 KB
INFO: Analysis reports compressed in 34ms, zip size=9 KB
INFO: Analysis report uploaded in 345ms
INFO: ANALYSIS SUCCESSFUL, you can browse http://127.0.0.1:55075/dashboard/index/reuseReport
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at http://127.0.0.1:55075/api/ce/task?id=AWVmqa2Hj2lG-KH_XkRQ
INFO: Task total time: 3.788 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 5.872s
INFO: Final Memory: 51M/396M
INFO: ------------------------------------------------------------------------
08:02:00.920 INFO  Waiting for analysis reports to be integrated
08:02:02.015 INFO  Waiting for analysis reports to be integrated
> 2018.08.23 08:02:02 INFO  ce[AWVmqa2Hj2lG-KH_XkRQ][o.s.c.t.CeWorkerImpl] Execute task | project=reuseReport | type=REPORT | id=AWVmqa2Hj2lG-KH_XkRQ
08:02:03.108 INFO  Waiting for analysis reports to be integrated
> 2018.08.23 08:02:04 INFO  ce[AWVmqa2Hj2lG-KH_XkRQ][o.s.c.t.CeWorkerImpl] Executed task | project=reuseReport | type=REPORT | id=AWVmqa2Hj2lG-KH_XkRQ | time=1856ms
08:02:04.586 INFO  Execute: /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/sonar-scanner-2.8/bin/sonar-scanner -e -Dsonar.clover.reportPath=clover.xml -Dsonar.sourceEncoding=UTF-8 -Dsonar.projectName=groovy-clover-sample -Dsonar.projectKey=groovy-clover-sample -Dsonar.language=grvy -Dsonar.host.url=http://127.0.0.1:55075 -Dsonar.projectVersion=1.0 -Dsonar.sources=src/main/groovy -Dsonar.scm.disabled=true
INFO: Option -e/--errors is no longer supported and will be ignored
INFO: Scanner configuration file: /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/target/sonar-scanner-2.8/conf/sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: SonarQube Scanner 2.8
INFO: Java 1.8.0_171 Oracle Corporation (64-bit)
INFO: Mac OS X 10.12.6 x86_64
INFO: User cache: /Users/ms185252/.sonar/cache
INFO: Publish mode
INFO: Load global settings
INFO: Load global settings (done) | time=62ms
INFO: Server id: AWVmqU7Bj2lG-KH_Xj3z
INFO: User cache: /Users/ms185252/.sonar/cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=41ms
INFO: SonarQube server 6.7.1
INFO: Default locale: "en_US", source code encoding: "UTF-8"
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=73ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=24ms
INFO: Load active rules
INFO: Load active rules (done) | time=231ms
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=24ms
INFO: Project key: groovy-clover-sample
INFO: -------------  Scan groovy-clover-sample
INFO: Load server rules
INFO: Load server rules (done) | time=68ms
INFO: Base dir: /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/projects/groovy-clover-sample
INFO: Working dir: /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/projects/groovy-clover-sample/.sonar
INFO: Source paths: src/main/groovy
INFO: Source encoding: UTF-8, default locale: en_US
INFO: Language is forced to grvy
INFO: Index files
WARN: File '/Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/projects/groovy-clover-sample/src/main/groovy/org/sonar/Helper.java' is ignored because it doesn't belong to the forced language 'grvy'
INFO: 1 file indexed
INFO: Quality profile for grvy: rules
INFO: Sensor Clover Coverage Analysis [clover]
INFO: Parsing /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/projects/groovy-clover-sample/clover.xml
INFO: Matched files in report : 100%
INFO: Sensor Clover Coverage Analysis [clover] (done) | time=124ms
INFO: Sensor GroovySensor [groovy]
WARN: Metric 'lines' is an internal metric computed by SonarQube. Provided value is ignored.
INFO: GMetrics completed: 628ms
INFO: Sensor GroovySensor [groovy] (done) | time=1076ms
INFO: Sensor GroovySurefireSensor [groovy]
INFO: parsing /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/projects/groovy-clover-sample/target/surefire-reports
WARN: Reports path not found: /Users/ms185252/ncrdev/git-repos/sonar-clover/its/plugin/projects/groovy-clover-sample/target/surefire-reports
INFO: Sensor GroovySurefireSensor [groovy] (done) | time=1ms
INFO: Sensor Groovy CoberturaSensor [groovy]
INFO: No Cobertura report provided (see 'sonar.groovy.cobertura.reportPath' property)
INFO: Sensor Groovy CoberturaSensor [groovy] (done) | time=0ms
INFO: Sensor Groovy JaCoCo [groovy]
INFO: Sensor Groovy JaCoCo [groovy] (done) | time=0ms
INFO: Sensor Groovy JaCoCo IT [groovy]
INFO: Sensor Groovy JaCoCo IT [groovy] (done) | time=1ms
INFO: Sensor Groovy JaCoCo Overall [groovy]
INFO: Sensor Groovy JaCoCo Overall [groovy] (done) | time=0ms
INFO: Sensor SonarJavaXmlFileSensor [java]
INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=1ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=9ms
INFO: Sensor CPD Block Indexer
INFO: Sensor CPD Block Indexer (done) | time=0ms
INFO: SCM Publisher is disabled
INFO: 1 file had no CPD blocks
INFO: Calculating CPD for 0 files
INFO: CPD calculation finished
INFO: Analysis report generated in 68ms, dir size=10 KB
INFO: Analysis reports compressed in 14ms, zip size=4 KB
INFO: Analysis report uploaded in 26ms
INFO: ANALYSIS SUCCESSFUL, you can browse http://127.0.0.1:55075/dashboard/index/groovy-clover-sample
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at http://127.0.0.1:55075/api/ce/task?id=AWVmqctnj2lG-KH_XkRX
INFO: Task total time: 2.391 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 3.588s
INFO: Final Memory: 57M/394M
INFO: ------------------------------------------------------------------------
08:02:08.628 INFO  Waiting for analysis reports to be integrated
08:02:09.709 INFO  Waiting for analysis reports to be integrated
> 2018.08.23 08:02:10 INFO  ce[AWVmqctnj2lG-KH_XkRX][o.s.c.t.CeWorkerImpl] Execute task | project=groovy-clover-sample | type=REPORT | id=AWVmqctnj2lG-KH_XkRX
> 2018.08.23 08:02:10 INFO  ce[AWVmqctnj2lG-KH_XkRX][o.s.c.t.CeWorkerImpl] Executed task | project=groovy-clover-sample | type=REPORT | id=AWVmqctnj2lG-KH_XkRX | time=500ms
08:02:10.834 INFO  Stop server
> 2018.08.23 08:02:11 INFO  app[][o.s.a.SchedulerImpl] Stopping SonarQube
> 2018.08.23 08:02:11 INFO  ce[][o.s.p.StopWatcher] Stopping process
> 2018.08.23 08:02:11 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is stopping...
> 2018.08.23 08:02:11 INFO  ce[][o.s.c.t.CeProcessingSchedulerImpl] Waiting for workers to finish in-progress tasks
> 2018.08.23 08:02:13 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is stopped
> 2018.08.23 08:02:14 INFO  app[][o.s.a.SchedulerImpl] Process [ce] is stopped
> 2018.08.23 08:02:14 INFO  web[][o.s.p.StopWatcher] Stopping process
> 2018.08.23 08:02:17 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
> 2018.08.23 08:02:17 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
> 2018.08.23 08:02:17 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
> 2018.08.23 08:02:17 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
08:02:18.034 INFO  Deregistering jdbc driver: org.h2.Driver@351d0846

Process finished with exit code 0
```

**Comment by Tony-Proum** [comment]
Oh, sorry  @mlschechter, I ran the wrong version of the plugin in my test case (I used another branch) Also, I cannot find a way to clone the repository you have used to create the pull request (in order to checkout your revision) Is it a private repository or something like that ?

**Comment by Tony-Proum** [comment]
Hi, this issue is now fixed using version 4.1 https://github.com/sfeir-open-source/sonar-clover/releases/tag/4.1
